version: '3.9'
services:
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres-db:
    image: postgres:14
    container_name: open-music-db
    environment:
      POSTGRES_DB: openmusicapp
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
